title: Coptic.io
email: abanobmikaeel@gmails.com
description: >- # this means to ignore newlines until "baseurl:"
  Coptic.io Documentation Site
baseurl: '' # the subpath of your site, e.g. /blog
twitter_username: jekyllrb
github_username: abanobmikaeel

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
